#!/usr/bin/env python


import sys
from rosinstall.rosinstall_cli import rosinstall_main
from rosinstall.helpers import ROSInstallException
from rosinstall.common import MultiProjectException

if __name__ == "__main__":
  try:
    sys.exit(not rosinstall_main(sys.argv))
  except ROSInstallException as e:
    sys.stderr.write("ERROR in rosinstall: %s"%str(e))
    sys.exit(1)
  except MultiProjectException as e:
    sys.stderr.write("ERROR in config: %s"%str(e))
    sys.exit(1)
