#!/usr/bin/env python

import sys
try:
  from rosinstall.rosinstall_cli import rosinstall_main
  from rosinstall.helpers import ROSInstallException
  from rosinstall.common import MultiProjectException
except ImportError as e:
  sys.stderr.write("ERROR Cannot find rosinstall libraries, check your\
 installation. One frequent cause is that rosinstall 0.5 is still\
 installed in /usr/local/lib. Check the rosinstall wiki for solutions.\n%s\n"%e)
  sys.exit(1)
  
if __name__ == "__main__":
  try:
    sys.exit(not rosinstall_main(sys.argv))
  except ROSInstallException as e:
    sys.stderr.write("ERROR in rosinstall: %s"%str(e))
    sys.exit(1)
  except MultiProjectException as e:
    sys.stderr.write("ERROR in config: %s"%str(e))
    sys.exit(1)
